name: GitHub Actions Demo
on: [push]
jobs:
  test-and-build:
    # TODO: test...
    runs-on: ubuntu-latest
    steps:
      - run: echo " Job started by a ${{ github.event_name }}"
#      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - run: ls ${{ github.workspace }}
      - run: ls target
      - run: ls target/x86_64-unknown-linux-musl
      - run: zip -j charger-alert.zip ./target/x86_64-unknown-linux-musl/release/charger-alert

#jobs:
#  test-and-build:
#    name: Rust project
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --release --all-features