name: Charger Alert Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master

# Rust build downloads a docker image - could cache that as well?

env:
  PROJECT_NAME: charger_alert
  AWS_REGION: eu-west-1

jobs:
  test:
    strategy:
      matrix:
        test-type: [ charger, cdk ]
        include:
          - test-type: charger
            test-command: cargo test
          - test-type: cdk
            test-command: zip add_alert.zip LICENSE && zip check_charger.zip LICENSE && cd infra && npm i && npm test # fake zips as 'code' for the Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test ${{ matrix.test-type }}
        run: ${{ matrix.test-command }}

  build:
    strategy:
      matrix:
        build-type: [ adder, checker ]
        include:
          - build-type: adder
            build-bin-name: add_alert
          - build-type: checker
            build-bin-name: check_charger
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup Rust and the correct target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          key: ${{ env.PROJECT_NAME }}-build-cache
          path: |
            ./target/release
#      - name: temp?
#        run: apt-get install libssl-dev
      - name: Build Rust release
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl -p ${{ matrix.build-bin-name }}
      - name: Zip ${{ matrix.build-type }} release
        run: mv ./target/x86_64-unknown-linux-musl/release/${{ matrix.build-bin-name }} ./bootstrap && zip -j ${{ matrix.build-bin-name }}.zip ./bootstrap
      - name: Upload ${{ matrix.build-type }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build-bin-name }}_build
          path: ./${{ matrix.build-bin-name }}.zip

  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download add alert
        uses: actions/download-artifact@v3
        with:
          name: add_alert_build
      - name: Download check charger
        uses: actions/download-artifact@v3
        with:
          name: check_charger_build
      - name: Deploy to AWS
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: infra
          cdk_subcommand: deploy
          cdk_args: --require-approval never
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
